### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by nWidart** [dowilcox/KnpMenu-Laravel#1]
Hello,

This may be a stupid question, but I was wondering how the menu structure in database looks like ? I don't see any migration files here or on the main knp/menu package.

Thanks

**Comment by dowilcox** [comment]
I haven't used a database with this yet but thinking off the top of my head you could do something like:

Menus Table:
id: int
name: varchar

Links Table:
id: int
menu_id: int
parent_id: int|nullable
title: varchar
url: text

The parent_id in the links table would point to another link in the links table if the item has a dropdown menu.
