### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by loiclavoie** [dowilcox/KnpMenu-Laravel#2]
In your code, at the KnpMenu\MenuServiceProvider::register, you use the following
`$renderOptions = $app['config']['menu.render'];`

Since there's no mention of creating configuration in your bundles (within Laravel5), the whole thing crash since he return null instead of an empty array.

I recommand adding to the documentation the proper configuration required and validate wether the configuration is set or not. If not, $renderOptions = [] (instead of null). This would prevent the error.

**Comment by dowilcox** [comment]
Running `php artisan vendor:publish` will publish the config file. I will update the readme. 

I think I might implement `$this->mergeConfigFrom()` that way publishing the config file won't be needed unless a setting needed to be changed.

**Comment by loiclavoie** [comment]
My apology (new to Laravel).

I've noted the comment and will retry.
